bed:
    name: bed
    script: farm/house/bedroom/bed.wtxt
desk:
    name: desk
    script: farm/house/bedroom/desk.wtxt
map:
    name: map on wall
    script: farm/house/bedroom/map.wtxt
rice:
    name: Rice
    script: farm/house/living_room/Rice.wtxt
henry:
    name: Henry
    script: farm/shop/Henry.wtxt
duke:
    name: Duke
    script: farm/meadow/Duke.wtxt
hereford:
    name: Hereford
    script: farm/meadow/Hereford.wtxt
