## Forest objects
    ## Forest Cabin
bethy:
    name: Bethy
    script: Kappallanoah Forest/forest cabin/Bethy.txt
draymond:
    name: Draymond
    script: Kappallanoah Forest/forest cabin/Draymond.txt
gerald:
    name: Gerald
    script: Kappallanoah Forest/forest cabin/Gerald.txt
informationBooklet:
    name: information booklet
    script: Kappallanoah Forest/forest cabin/information booklet.txt
poster:
    name: poster
    script: Kappallanoah Forest/forest cabin/poster.txt
    ## Lumber Mill
jack:
    name: Jack
    script: Kappallanoah Forest/lumber mill/Jack.txt
olWilly:
    name: Ol' Willy
    script: Kappallanoah Forest/lumber mill/Ol' Willy.txt
    ## Abandoned Forest
diary:
    name: diary
    script: Kappallanoah Forest/abandoned treehouse/diary.txt
familyPhoto:
    name: family photo
    script: Kappallanoah Forest/abandoned treehouse/family photo.txt
recipe:
    name: recipe
    script: Kappallanoah Forest/abandoned treehouse/recipe.txt
automaticRifle:
    name: automatic rifle
    script: Kappallanoah Forest/abandoned treehouse/rifle.txt
    showIf: not_inventory_rifle
cot:
    name: cot
    script: Kappallanoah Forest/abandoned treehouse/cot.txt
    ## Hunting Range
tucker:
    name: Tucker
    script: Kappallanoah Forest/hunting range/tucker.txt
