catFood:
    name: cat food
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseCatFood.txt
closet:
    name: closet
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseCloset.txt
loreDoor:
    name: front door
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseDoor.txt
bed:
    name: bed
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseBed.txt
dresser:
    name: dresser
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseDresser.txt
radio:
    name: radio
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseRadio.txt
keys:
    name: keys
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseKeys.txt
    showIf:
      and:
        - subClosetOpen
        - subSawKeys
        - not_inventory_loreKeys
stackPapers:
    name: stack of papers
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHousePapers.txt
junkMail:
    name: junk mail
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseJunkMail.txt
picture:
    name: picture
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHousePicture.txt
pillBottles:
    name: pill bottles
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHousePillBottles.txt
wallet:
    name: wallet
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseWallet.txt
    showIf: not_inventory_loreWallet
marthi:
    name: Marthi
    script: Lore/Beginning/Suburbs/Lore's House/People/Beginning_LoreHouseMarthi.txt
mirror:
    name: mirror
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseMirror.txt
toilet:
    name: toilet
    script: Lore/Beginning/Suburbs/Lore's House/Items/Beginning_LoreHouseToilet.txt
hal:
    name: Hal
    script: Lore/Beginning/Suburbs/People/Beginning_LoreSuburbsHal.txt

tree:
    name: tree
    script: Lore/Suburbs/Tree.txt
doorbell:
    name: doorbell
    script: Lore/Suburbs/doorbell.txt
glover:
    name: Glover
    script: Lore/Suburbs/Glover.txt
    showIf:
        or:
            - subDidCutTree_eq_1
            - subCanRingDoorbell_eq_1
pinkGuy:
    name: Pink Guy
    script: Lore/Suburbs/Pink Guy.txt
peevedPeople:
    name: peeved people
    script: Lore/Suburbs/Peeved People.txt
pileOfMoney:
    name: pile of money
    script: Lore/Suburbs/pile of money.txt
    showIf: inventory_money_eq_0
flamethrower:
    name: flamethrower
    script: Lore/Suburbs/Flamethrower.txt
    showIf: inventory_flamethrower_eq_0
window:
    name: window
    script: Lore/Suburbs/window.txt
nolan:
    name: Nolan
    script: Lore/Suburbs/Nolan.txt
zweihander:
    name: zweihander
    script: Lore/Suburbs/Zweihander.txt
    showIf: inventory_zweihander_eq_0
shin:
    name: shin
    script: Lore/Suburbs/shin.txt
bandages:
    name: bandages
    script: Lore/Suburbs/bandages.txt
    showIf: inventory_money_eq_0
solaire:
    name: Solaire
    script: Lore/Suburbs/solaire.txt
    showIf: subKnocked
samjam:
    name: Samjam
    script: Lore/Suburbs/samjam.txt
    showIf: subLove_eq_0