## The mappings for each area in the game. Each area corresponds to multiple
## rooms, which in turn has multiple objects. The rooms and objects are
## associated through the roomsConfig and objectsConfig fields

# area id
suburbs:
    # readable name
    name: Residential District
    # room config path
    roomsConfig: rooms/suburbs.yml
    # object config path
    objectsConfig: objects/suburbs.yml
    # which world map (0=Lore, 1=Kipp)
    mapId: 0
    # in area map art path
    inAreaMap: aspire.txt
    # list of entrances to area (room id and coordinates on world map)
    entrances:
        -
            roomId: busStop
            r: 18
            c: 14

university:
    name: University
    roomsConfig: rooms/university.yml
    objectsConfig: objects/university.yml
    mapId: 0
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: diningHall
            r: 30
            c: 39

downtown:
    name: Downtown
    roomsConfig: rooms/downtown.yml
    objectsConfig: objects/downtown.yml
    mapId: 0
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: businessDistrict
            r: 15
            c: 26

aspire:
    name: Aspire
    roomsConfig: rooms/aspire.yml
    objectsConfig: objects/aspire.yml
    mapId: 1
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: townCenter
            r: 9
            c: 116

farm:
    name: Charli
    roomsConfig: rooms/farm.yml
    objectsConfig: objects/farm.yml
    mapId: 1
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: meadow
            r: 22
            c: 127

blackHills:
    name: Black Hills
    roomsConfig: rooms/black_hills.yml
    objectsConfig: objects/black_hills.yml
    mapId: 1
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: railwayStation
            r: 30
            c: 97

meadows:
    name: Uncanny Prairie
    roomsConfig: rooms/meadows.yml
    objectsConfig: objects/meadows.yml
    mapId: 1
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: shepherdHouse
            r: 20
            c: 62
        -
            roomId: cliffside
            r: 15
            c: 55

badlands:
    name: The Good Badlands
    roomsConfig: rooms/badlands.yml
    objectsConfig: objects/badlands.yml
    mapId: 1
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: campsite
            r: 22
            c: 36

        -
            roomId: cave6
            r: 8
            c: 34

forest:
    name: Kappallanoah Forest
    roomsConfig: rooms/forest.yml
    objectsConfig: objects/forest.yml
    mapId: 1
    inAreaMap: aspire.txt
    entrances:
        -
            roomId: forestCabin
            r: 19
            c: 89
        -
            roomId: huntingRange
            r: 21
            c: 77
