# data corresponding to the library node
library:
    # readable name of room
    name: County Library
    # description of room
    description: Contains a host of books and digital media
    # row on map text file where room is
    r: 0
    # column on map text file where room is
    c: 0
    # list of neighboring nodes
    neighbors:
        # store node is located to the east, meaning right arrow key should be pressed to hover there
        store: E
        # town_square is located to south, meaning down arrow key should be pressed to hover there
        town_square: S
store:
    name: Grocery Store
    description: Where all the city gets its produce
    r: 0
    c: 3
    neighbors:
        library: W
town_square:
    name: Town Square
    description: Filled with tourists and merchants
    r: 3
    c: 0
    neighbors:
        library: N
        bar: E
bar:
    name: Tavern
    description: Local watering hole
    r: 3
    c: 5
    neighbors:
        town_square: W
