## Information regarding items that can appear in the inventory

## Begin Suburbs items
loreKeys:
    name: keys
    description: Keys to the house. Never leave home without them.
loreWallet:
    name: wallet
    description: Filled with the essential notes and documentation you need in a civilization.
letterFromFriends:
    name: letter from friends
    description: "\"Lore, please come meet us at the university, we have some news for you. We can catch up at the dining hall. With love -- Rune, Quen, and Essa\""
afro:
    name: afro
    description: A nice, thick afro. Inscribed inside is "Wow queen, you're so beautiful".
morphine:
    name: morphine
    description: A lil something to ease the pain of living.
money:
    name: money
    description: A nice fat stash of cash. The safest way to double your money is to fold it over and put it in your pocket.
flamethrower:
    name: flamethrower
    description: A brand new flamethrower, fit for duty! Good for roasting fools.2
zweihander:
    name: zweihander
    description: As the name suggests, the Zweihander is held with two hands, buts its wielder must still be inhumanly strong. It is this great weight that sends foes flying when hit solidly.
bandages:
    name: bandages
    description: Some good ol bandages to fix any injury.
blueCrystal:
    name: blue crystal
    description: The blue crystal releases feelings of justice and friendliness.
redCrystal:
    name: red crystal
    description: Hatred and wrath oozes from this crystal.
greenCrystal:
    name: green crystal
    description: This crystal reflects wisdom and good intentions.
lightsaber:
    name: lightsaber
    description: Made using the crystal, the lightsaber is the ultimate sword. May the force be with you.
## End Suburbs items

## Begin Aspire items
randomToken:
    name: random token
    description: "It's a little dirty from the dried mud stains, but you can make out a picture of a bottle with the description: \"Good for 1 drink.\""
fireAle:
    name: fire ale
    description: The description says, "Gives you the spirit of a fire breathing dragon." Maybe it's just an ad marketing trick, or maybe...
ticket:
    name: ticket
    description: It says, "ONE PHOENIX BOLT. Only acceptable at Aspire Saloon. This establishment is not responsible if fed to an actual phoenix." Wonder how they got that disclaimer on there.
phoenixBolt:
    name: Phoenix Bolt
    description: Says here that it's brewed with barley and the seeds of world's hottest pepper. How can anyone stomach this?
mohanisBullets:
    name: Mohani's bullets
    description: "I wonder why she would carve the number 6 on her shells?"
revolver:
    name: six-chamber revolver
    description: Strange how the Rune Raiders just let me have this. Guess magic is stronger than the mortal world. I have enough bullets for two reloads.
tomahawk:
    name: tomahawk
    description: Looks sharp enough to make a dent in a tree like our machete back home. Hopefully I won't have to test if it works with bodies, too.
## End Aspire items

## Begin badlands items
lighter:
    name: lighter
    description: It's a small lighter like the one my dad use to keep beside his box of cigarettes. Operates like one, too.
extinguisher:
    name: extinguisher
    description: A fire extinguisher...to put out fires. Not much else to it.
map:
    name: map
    description: "Yup. It's right here: cave 6 is accessible through that tunnel marked on the map. And that's how I'm  gonna reference it."
## End badlands items

## Begin farm items
dirtyMap:
    name: dirty map
    description: An old, dusty map detailing a vast expanse of wilderness. Contains dragons and other such mythical beasts at the corners.
farmcraft:
    name: Farmcraft
    description: A game that you can sink infinite amounts of time into and yet still be n00bish.
milk:
    name: milk
    description: Whole milk! None of that 2% nonsense.

## End farm items

## Begin Black Hills items
letterToThomas:
    name: letter to Thomas
    description: Probably not best to read through others' mail.
bucketOfMoonshine:
    name: bucket of moonshine
    description: Looks sort of appetizing, but not sure I'd trust this.
dragonskinBoots:
    name: dragonskin boots
    description: I thought dragons were a myth. This seems like some sort of scam.
corrosiveGas:
    name: corrosive gas
    description: Deadly, and, um, that's all I know.
corrosiveShotgun:
    name: corrosive shotgun
    description: I might get convicted of war crimes if I fool around with this.
## End Black Hills items

## Begin Kappallanoah Forest items
automaticRifle:
    name: rifle
    description: It was Kipp's father's old automatic rifle. It still works and might come in use later.
# End Kappallanoah Forest items

