## Mappings for the keybindings in different situations in the game
## These will be displayed in the Help window
## Note that these are not actually bound to InputHandler, and are only for display

isLoading: {}
titleScreen: {}
selectFile:
    - ArrowKeys: Browse options
    - Return: Confirm option
credits:
    - Return: Exit
inAreaCommand:
    - TextKeys: Form command
    - Return: Execute command
    - PageUp/Down: Scroll history
    - Tab: Autocomplete
inAreaChoice:
    - ArrowKeys: Browse choice
    - Return: Confirm choice
inAreaInput:
    - TextKeys: Form input
    - Return: Confirm input
    - PageUp/Down: Scroll history
inAreaMap:
    - ArrowKeys: Browse rooms
    - Return: Exit
inAreaInventory:
    - ArrowKeys: Browse items
    - Return: Exit
inAreaAnimating:
    - Space(Hold): Fast Scroll
worldMap:
    - ArrowKeys: Move
worldMapOverArea:
    - ArrowKeys: Move
    - Return: Enter Area
