## Mappings for the keybindings in different situations in the game
## These will be displayed in the Help window
## Note that these are not actually bound to InputHandler, and are only for display

IsLoading: {}
TitleScreen: {}
SelectFile: {}
Credits: {}
Settings: {}
InAreaCommand:
    - TextKeys: Form command
    - Return: Execute command
    - PageUp/Down: Scroll history
    - Tab: Autocomplete
InAreaChoice:
    - ArrowKeys: Browse choices
    - Return: Confirm choice
    - PageUp/Down: Scroll history
InAreaInput:
    - TextKeys: Form input
    - Return: Confirm input
    - PageUp/Down: Scroll history
InAreaMap:
    - ArrowKeys: Browse rooms
    - Return: Exit
InAreaInventory:
    - ArrowKeys: Browse items
    - Return: Exit
InAreaAnimating:
    - Space(Hold): Fast Scroll
WorldMap:
    - ArrowKeys: Move
WorldMapOverArea:
    - ArrowKeys: Move
    - Return: Enter Area
