## Mappings for the keybindings in different situations in the game
## These will be displayed in the Help window
## Note that these are not actually bound to InputHandler, and are only for display

isLoading: {}
titleScreen: {}
selectFile:
    - Arrow keys: Browse options
    - Return: Confirm option
credits:
    - Return: Exit
inAreaCommand:
    - Printable keys: Form command
    - Backspace: Deform command
    - Return: Execute command
inAreaChoice:
    - Arrow keys: Browse choice
    - Return: Confirm choice
inAreaInput:
    - Printable keys: Form input
    - Backspace: Deform input
    - Return: Confirm input
inAreaMap:
    - Arrow keys: Browse rooms
    - Return: Exit
inAreaInventory:
    - Arrow keys: Browse items
    - Return: Exit
inAreaAnimating: {}
worldMap:
    - Arrow keys: Move
worldMapOverArea:
    - Arrow keys: Move
    - Return: Enter Area
