language: python
python:
    - "3.5"
install:
    - pip install nose
    - pip install pyyaml
script: nosetests src/tests.py
notifications:
    email:
        on_success: never
        on_failure: change
