## Aspire rooms

bank:
    name: bank
    mapName: Bank - Town Treasury
    description: Withholding the town's source of funding; currently being held off by the Chikasi Clan.
    script: aspire/Rooms/bank.txt
    r: 1
    c: 9
    showIf: ntoQuestStart
    neighbors:
        - library
        - townCenter
        - saloon
    objects:
        - akecheta
        - totemPole
        - painting
library:
    name: library
    mapName: Library
    description: All of the town's knowledge can be found here; being used as a makeshift hideaway from Rowen and his cliques.
    script: aspire/Rooms/library.txt
    r: 3
    c: 9
    neighbors:
        - bank
        - townCenter
    objects:
        - arthur
        - sleepingBag
        - bookshelf
        - baseNumbersBook
        - encyclopediaBook
        - scientificBook
saloon:
    name: saloon
    mapName: "Saloon: Brews & Blends"
    description: Bringing the town alcohol from lands far and wide; currently being held off by the Smoking Gun.
    script: aspire/Rooms/saloon.txt
    r: 1
    c: 5
    showIf: ntoQuestStart
    neighbors:
        - bank
        - townCenter
        - gunshop
    objects:
        - flint
        - lineOfBottles
        - bartender
        - ticketMachine
        - exMember
gunshop:
    name: gunsmith shop
    mapName: Gunsmith
    description: Crafting gear and guns since '71; currently being held off by the Rune Raiders.
    script: aspire/Rooms/gunsmith shop.txt
    r: 3
    c: 3
    showIf: ntoQuestStart
    neighbors:
        - saloon
        - townCenter
    objects:
        - mohani
        - forge
        - glassOfWater
        - revolver
townCenter:
    name: town center
    mapName: Town Center
    description: Accessible to and from all shops and establishments; not the nicest place to be in a shootout.
    script: aspire/Rooms/town center.txt
    r: 3
    c: 7
    neighbors:
        - bank
        - library
        - saloon
        - gunshop
    objects:
        - rowen
        - townSign
