campsite:
    name: Campsite
    description: n/a
    script: badlands/Rooms/Campsite.txt
    r: 0
    c: 0
    neighbors:
        - tau
        - upsilon
        - sigma
        - mu
        - kappa
        - cave6 # HAS TO BE HIDDEN UNTIL THE MAP IS ADDED TO INVENTORY
    objects:
        - sleepingBag

tau:
    name: Tau
    description: n/a
    script: badlands/Rooms/Tau.txt
    r: 0
    c: 0
    neighbors:
        - campsite
    objects:
        - torch

upsilon:
    name: Upsilon
    description: n/a
    script: badlands/Rooms/Upsilon.txt
    r: 0
    c: 0
    neighbors:
        - campsite
    objects: {}

sigma:
    name: Sigma
    description: n/a
    script: badlands/Rooms/Sigma.txt
    r: 0
    c: 0
    neighbors:
        - campsite
    objects:
        - firewall

mu:
    name: Mu
    description: n/a
    script: badlands/Rooms/Mu.txt
    r: 0
    c: 0
    neighbors:
        - campsite
    objects: {}

kappa:
    name: Kappa
    description: n/a
    script: badlands/Rooms/Kappa.txt
    r: 0
    c: 0
    neighbors:
        - campsite
    objects: {}

cave6:
    name: Cave 6
    description: n/a
    script: badlands/Rooms/Cave 6.txt
    showIf: inventory_map_eq_1
    r: 0
    c: 0
    neighbors:
        - campsite
    objects:
        - wallPuzzle
