## Black Hills rooms

railwayStation:
    name: Railway Station
    description: n/a
    script: Black Hills/train station/train station.txt
    r: 0
    c: 0
    neighbors:
        - generalStore
    objects:
        - conney
        - thomas
        - toddAndZodd
        - trainSchedule
        - wantedSign
generalStore:
    name: General Store
    description: n/a
    script: Black Hills/general store/general store.txt
    r: 0
    c: 0
    neighbors:
        - railwayStation
        - hospital
    objects:
        - druGeneral
        - gritt
        - kaven
        - newspaper
        - poster
hospital:
    name: Hospital
    description: n/a
    script: Black Hills/hospital/hospital.txt
    r: 0
    c: 0
    neighbors:
        - generalStore
        - townTreasury
        - miningCompany
    objects:
        - baha
        - flyer
        - rani
        - rosanto
        - table
        - bed
townTreasury:
    name: Town Treasury
    description: n/a
    script: Black Hills/town treasury/town treasury.txt
    r: 0
    c: 0
    neighbors:
        - hospital
    objects:
        - bronzeShovel
        - silverPitchfork
        - gold
        - druTreasury
        - marshall
miningCompany:
    name: Mining Company
    description: n/a
    script: Black Hills/mining warehouse/mining warehouse.txt
    r: 0
    c: 0
    neighbors:
        - hospital
    objects:
        - book
        - corrosiveGas
        - passwordLock
        - shotgunPete
        - widowmaker
