# Business District
businessDistrict:
    name: Business District
    description: n/a
    script: Lore/Downtown/Rooms/Downtown_Lore_BusinessDistrict.txt
    r: 0
    c: 0
    neighbors:
        - industrialDistrict
        - rodninOffice
    objects: {}

officeDesk:
    name: Desk
    description: n/a
    script: Lore/Beginning/Downtown/Rooms/Beginning_LoreDowntownOfficeDesk.txt
    r: 0
    c: 0
    neighbors:
        - rodninOffice
        - insideElevator
    objects:
        - secretary

rodninOffice:
    name: Office
    description: n/a
    script: Lore/Beginning/Downtown/Rooms/Beginning_LoreDowntownRodninOffice.txt
    r: 0
    c: 0
    neighbors:
        - businessDistrict
        - officeDesk
        - insideElevator
    objects: {}

insideElevator:
    name: elevator
    description: n/a
    script: Lore/Beginning/Downtown/Rooms/InsideElevator.txt
    r: 0
    c: 0
    neighbors:
        - officeDesk
        - rodninOffice
    objects:
        - liftAttendant

rodninOfficeSecondFloor:
    name: Second Floor
    description: n/a
    script: Lore/Beginning/Downtown/Rooms/Beginning_LoreDowntownSecondFloorRodninOffice.txt
    r: 0
    c: 0
    neighbors:
        - insideElevator
    objects:
        - rodnin
        - tempBed

rodninOfficeThirdFloor:
    name: Lab
    description: n/a
    script: Lore/Beginning/Downtown/Rooms/Beginning_LoreDowntownOfficeFloor3.txt
    r: 0
    c: 0
    neighbors:
        - rodninOfficeThirdFloorShelf
        - insideElevator
    objects:
        - dataSamples

rodninOfficeThirdFloorShelf:
    name: Third Floor
    description: n/a
    script: Lore/Beginning/Downtown/Rooms/Beginning_LoreDowntownOfficeFloor3_Shelf.txt
    r: 0
    c: 0
    neighbors:
        - rodninOfficeThirdFloor
    objects:
        -oFMRP
        -ePF

# Industrial District
industrialDistrict:
    name: Industrial District
    description: n/a
    script: Lore/Downtown/Rooms/Downtown_Lore_IndustrialDistrict.txt
    r: 0
    c: 0
    neighbors:
        - businessDistrict
        - hangar
    objects: {}

hangar:
    name: Hangar
    description: n/a
    script: Lore/Downtown/Rooms/Downtown_Lore_IndustrialDistrict_Hangar.txt
    r: 0
    c: 0
    neighbors:
        - industrialDistrict
        - upperLevel
    objects:
        - controlPanel


upperLevel:
    name: Upper Level
    description: n/a
    script: Lore/Downtown/Rooms/Downtown_Lore_IndustrialDistrict_Hangar_UpperLevel.txt
    r: 0
    c: 0
    neighbors:
        - hangar
    objects: {}
