bedroom:
    name: bedroom
    description: n/a
    script: farm/house/bedroom/bedroom.wtxt
    r: 0
    c: 0
    neighbors:
        - livingRoom
    objects:
        - bed
        - map

livingRoom:
    name: living room
    description: n/a
    script: farm/house/living_room/living_room.wtxt
    r: 0
    c: 0
    neighbors:
        - kitchen
        - bedroom
        - shop
        - meadow
    objects:
        - rice

kitchen:
    name: kitchen
    description: n/a
    script: farm/house/kitchen/kitchen.wtxt
    r: 0
    c: 0
    neighbors:
        - livingRoom
    objects: {}

shop:
    name: Shop
    description: n/a
    script: farm/shop/shop.wtxt
    r: 0
    c: 0
    neighbors:
        - livingRoom
    objects:
        - henry

meadow:
    name: Meadow
    description: n/a
    script: farm/meadow/meadow.wtxt
    r: 0
    c: 0
    neighbors:
        - livingRoom
    objects:
        - duke
        - hereford
