forestCabin:
    name: Forest Cabin
    description: n/a
    script: Kappallanoah Forest/forest cabin/forest cabin.txt
    r: 0
    c: 0
    neighbors:
        abandonedTreehouse: N
        lumberMill: S
        huntingRange: W
    objects:
        - bethy
        - draymond
        - gerald
        - informationBooklet
        - poster

abandonedTreehouse:
    name: Abandoned Treehouse
    description: n/a
    script: Kappallanoah Forest/abandoned treehouse/abandoned treehouse.txt
    r: 0
    c: 0
    neighbors:
        forestCabin: E
        lumberMill: S
        huntingRange: W
    objects:
        - diary
        - familyPhoto
        - recipe
        - automaticRifle
        - cot

lumberMill:
    name: Lumber Mill
    description: n/a
    script: Kappallanoah Forest/lumber mill/lumber mill.txt
    r: 0
    c: 0
    neighbors:
        forestCabin: E
        abandonedTreehouse: N
        huntingRange: W
    objects:
        - jack
        - olWilly

huntingRange:
    name: Hunting Range
    description: n/a
    script: Kappallanoah Forest/hunting range/hunting range.txt
    r: 0
    c: 0
    neighbors:
        forestCabin: E
        abandonedTreehouse: N
        lumberMill: S
        cave: NE
    objects:
        - tucker

cave:
    name: Mysterious Cave
    description: n/a
    script: Kappallanoah Forest/cave/cave.txt
    r: 0
    c: 0
    showIf: forTuckerTalk_eq_1
    neighbors:
        huntingRange: W
    objects: {}
