shepherdHouse:
    name: Shepherd House
    description: The only house around here. I wonder how the shepherd can take the silence so well.
    script: meadows/Rooms/Shepherd House.txt
    r: 0
    c: 0
    neighbors:
        - hedgeMazeEntrance
    objects:
        - queenBed

hedgeMazeEntrance:
    name: Hedge Maze Entrance
    description: Kipp has seen these types of mazes before in the corn patches, but none of them glowed like this before…
    script: meadows/Rooms/Hedge Maze Entrance.txt
    r: 0
    c: 0
    neighbors:
        - checkpoint1
        - checkpoint2
        - checkpoint3
        - checkpoint4
        - cliffside
    objects: {}

checkpoint1:
    name: Checkpoint 1
    description: The sound of tanks, guns, and horses fill the air. War has never been like this in Kipp's world.
    script: meadows/Rooms/Checkpoint 1.txt
    r: 0
    c: 0
    neighbors:
        - hedgeMazeEntrance
        - checkpoint2
    objects: {}

checkpoint2:
    name: Checkpoint 2
    description: The roar of music and celebration from a different era confuses the group, but sounds inviting.
    script: meadows/Rooms/Checkpoint 2.txt
    r: 0
    c: 0
    neighbors:
        - hedgeMazeEntrance
        - checkpoint3
    objects: {}

checkpoint3:
    name: Checkpoint 3
    description: The sound of a broken pipe whistles. The boiler room sets the scene for a slasher film, and guess who's the star.
    script: meadows/Rooms/Checkpoint 3.txt
    r: 0
    c: 0
    neighbors:
        - hedgeMazeEntrance
        - checkpoint4
    objects: {}

checkpoint4:
    name: Checkpoint 4
    description: The heat is on. With magma flowing beneath the floor, no one is going to survive here for long.
    script: meadows/Rooms/Checkpoint 4.txt
    r: 0
    c: 0
    neighbors:
        - hedgeMazeEntrance
        - cliffside
    objects: {}

cliffside:
    name: Cliffside
    description: The end is near, and it looks pretty cool. Over the horizon lies ahead...
    script: meadows/Rooms/Cliffside.txt
    r: 0
    c: 0
    neighbors:
        - hedgeMazeEntrance
    objects: {}
