bedroom:
    name: Bedroom
    description: n/a
    script: Lore/Beginning/Suburbs/Lore's House/Rooms/Beginning_LoreHouseBedroom.txt
    r: 0
    c: 0
    neighbors:
        - bathroom
        - hallway
    objects:
        - dresser
        - radio
        - bed

bathroom:
    name: Bathroom
    description: n/a
    script: Lore/Beginning/Suburbs/Lore's House/Rooms/Beginning_LoreHouseBathroom.txt
    r: 0
    c: 0
    neighbors:
        - bedroom
    objects:
        - mirror
        - toilet

hallway:
    name: Hallway
    description: n/a
    script: Lore/Beginning/Suburbs/Lore's House/Rooms/Beginning_LoreHouseHallway.txt
    r: 0
    c: 0
    neighbors:
        - bedroom
        - kitchen
    objects:
        - picture
        - closet
        - keys

livingRoom:
    name: Living Room
    description: n/a
    script: Lore/Beginning/Suburbs/Lore's House/Rooms/Beginning_LoreHouseLivingRoom.txt
    r: 0
    c: 0
    neighbors:
        - kitchen
        - mainStreet
    objects:
        - wallet
        - loreDoor
        - zweihander

kitchen:
    name: Kitchen
    description: n/a
    script: Lore/Beginning/Suburbs/Lore's House/Rooms/Beginning_LoreHouseKitchen.txt
    r: 0
    c: 0
    neighbors:
        - hallway
        - livingRoom
    objects:
        - catFood
        - pillBottles
        - stackPapers
        - junkMail
        - marthi

mainStreet:
    name: Main Street
    description: n/a
    script: Lore/Suburbs/Suburbs.txt
    r: 0
    c: 0
    neighbors:
        - livingRoom
        - gloverHouse
        - busStop
        - holeInWall
    showIf: subFinishedLoreHouse
    objects:
        - halBeginning

gloverHouse:
    name: Glover House
    description: n/a
    script: Lore/Suburbs/Gloverhouse.txt
    r: 0
    c: 0
    neighbors:
        - mainStreet
    objects:
        - doorbell
        - tree
        - glover

busStop:
    name: Bus Stop
    description: n/a
    script: Lore/Suburbs/bus stop.txt
    r: 0
    c: 0
    neighbors:
        - mainStreet
    objects: {}

holeInWall:
    name: Hole in the Wall
    description: n/a
    script: Lore/Suburbs/Hole in the Wall.txt
    r: 0
    c: 0
    neighbors:
        - mainStreet
        - outskirts
    objects:
        - pinkGuy

outskirts:
    name: Outskirts
    description: n/a
    script: Lore/Suburbs/Beyond the hole in the wall.txt
    r: 0
    c: 0
    neighbors:
        - nolanHouse
        - holeInWall
        - shinHouse
        - samjamHouse
    showIf: canVisitOutskirts
    objects: {}

nolanHouse:
    name: Nolan House
    description: n/a
    script: Lore/Suburbs/house1.txt
    r: 0
    c: 0
    neighbors:
        - outskirts
        - shinHouse
    objects:
        - peevedPeople
        - pileOfMoney
        - flamethrower
        - window

nolanBasement:
    name: Nolan Basement
    description: n/a
    script: Lore/Suburbs/NolanBasement.txt
    r: 0
    c: 0
    neighbors:
        - nolanHouse
    objects:
        - nolan

shinHouse:
    name: Shin House
    description: n/a
    script: Lore/Suburbs/ShinHouse.txt
    r: 0
    c: 0
    neighbors:
        - outskirts
        - insideShinHouse
        - nolanHouse
        - samjamHouse
    objects: {}

insideShinHouse:
    name: Inside Shin House
    description: n/a
    script: Lore/Suburbs/InsideShinHouse.txt
    r: 0
    c: 0
    neighbors:
        - shinHouse
    showIf: inventory_morphine_eq_1
    objects:
        - shin
        - bandages

samjamHouse:
    name: House of Samjam
    description: n/a
    script: Lore/Suburbs/samjamHouse.txt
    r: 0
    c: 0
    neighbors:
        - outskirts
        - shinHouse
        - frontGate
    objects: {}

frontGate:
    name: front gate
    description: n/a
    script: Lore/Suburbs/frontGate.txt
    r: 0
    c: 0
    neighbors:
        - samjamHouse
        - insideSamjam
    objects:
        - solaire

insideSamjam:
    name: Inside House Samjam
    description: n/a
    script: Lore/Suburbs/InsideSamjam.txt
    r: 0
    c: 0
    neighbors:
        - frontGate
    showIf: subSolaired_eq_1
    objects:
        - samjam
dungeon:
    name: Dungeon
    description: n/a
    script: Lore/Suburbs/dungeon.txt
    r: 0
    c: 0
    neighbors:
        - holeInWall
    objects: {}
